# -*- coding: utf-8 -*-
"""Day 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jCTtfo9w0KfoKO6SIwzIDeILQX8NGWan

# Python Data Types: Notes and Examples

In Python, we have different data types, such as **strings, integers, floats, and booleans**. Each has its own distinct features.

## 1. String Data Type (`str`)
A string consists of characters written between single or double quotes.

We can access a character at any position in a string using **indexing**. It is also important to note that we can use negative indexing (like `-1`) to traverse the string backward.
"""

dty1 = "string"
name = "Aali"

# Forward indexing (starts at 0)
print(name[0])
print(name[1])
print(name[2])
print(name[3])

# Backward indexing
print(name[-1])

"""## 2. Integer Data Type (`int`)
As the name suggests, the integer data type is used to represent whole numerical data.

### Important Distinction: Strings vs. Integers
When numbers are wrapped in quotes, Python treats them as strings. Using the `+` operator on them will **concatenate** (join) them instead of adding them mathematically.
"""

# String Concatenation
numer = "123"
digi = "345"
print(numer + digi)
print("This will concatenate, not add, as both numbers are written in double quotes and become strings.")

# Mathematical Addition
count = 123
counting = 456
print(count + counting)
print("The addition function is performed.")

"""### Formatting Large Numbers
Instead of using commas to separate digit spaces (which would cause a syntax error in Python), we use underscores (`_`). Python ignores the underscores when executing the code, making large numbers much easier for humans to read.
"""

bignum = 123_456_789
print("Instead of using commas to separate different digit spaces, we use '_':", bignum)

"""## 3. Float Data Type (`float`)
The float (floating-point) data type is used to represent real numbers that contain a decimal point.
"""

newnum = 123.34
print(newnum)

"""## 4. Boolean Data Type (`bool`)
The boolean data type has only two possible values: `True` and `False`.

> **Important Note:** Boolean values must start with a capital letter (`True`, not `true`) and are **not** wrapped in quotation marks. This lack of quotes is exactly what makes them distinct from strings.
"""

# Correct Boolean assignment
answ = True
print(answ)

"""## 5. The `type()` Function and Type Errors

### The `type()` Function
To determine and identify the data type of a specific variable or value, we use the built-in `type()` function.
"""

name = "Aali"
age = 22
graduate = True
CGPA = 9.5

print(type(name))      # Output: <class 'str'>
print(type(age))       # Output: <class 'int'>
print(type(graduate))  # Output: <class 'bool'>
print(type(CGPA))      # Output: <class 'float'>

"""### Type Errors
A `TypeError` occurs when you try to apply an operation or a function to a data type that does not support it.

For example, using `len(123)` will result in an error because `len()` is a function meant for sequences (like strings or lists), not for integers.
"""

# This will throw a TypeError: object of type 'int' has no len()
# len(123)

# Correct usage:
print(len("123"))  # Output: 3 (because it counts the characters in the string)

"""## 6. Type Conversion (Type Casting)

Type conversion is the process of changing a variable from one data type to another. There are two types: **Implicit** and **Explicit**.

### A. Implicit Type Conversion (Automatic)
This happens automatically when Python converts one data type into another without any user intervention.
* *Example:* When you take user input using the `input()` function, Python **implicitly** converts whatever the user types into a string data type.
* *Another Example:* If you add an integer and a float (`5 + 2.0`), Python automatically converts the result to a float (`7.0`).

### B. Explicit Type Conversion (Manual)
This happens when we manually change the data type ourselves using built-in functions like `int()`, `str()`, `float()`, or `bool()`. This is also known as **Type Casting**.
"""

# Explicit Conversion Example
age = "23"  # Currently a string

# We manually convert it to an int so we can perform math on it
print(int(age) + 2)  # Output: 25

"""## 7. Mathematical Operators in Python

Python uses standard symbols for basic math, but it also has a few special operators.

| Operator | Name | Description | Example | Result |
| :---: | :--- | :--- | :--- | :--- |
| `+` | Addition | Adds two values | `5 + 2` | `7` |
| `-` | Subtraction | Subtracts one value from another | `5 - 2` | `3` |
| `*` | Multiplication | Multiplies two values | `5 * 2` | `10` |
| `/` | Division | Divides and **always** returns a float | `5 / 2` | `2.5` |
| `//` | Floor Division | Divides and chops off the decimal (rounds down) | `5 // 2` | `2` |
| `**` | Exponentiation | Raises to a power (Exponent) | `5 ** 2` | `25` (5 squared) |
"""

# The difference between Division (/) and Floor Division (//)
print(6 / 3)   # Output: 2.0 (Notice it leaves a decimal)
print(6 // 3)  # Output: 2   (Chops off the decimal, returns an int)

print(7 // 3)  # Output: 2   (Chops off the .3333 part entirely)
print(2 ** 3)  # Output: 8   (2 cubed: 2 * 2 * 2)

"""### Operator Precedence: PEMDAS
When you have multiple operators in one line, Python follows the **PEMDAS** order of operations:
1. **P**arentheses `()`
2. **E**xponents `**`
3. **M**ultiplication `*` and **D**ivision `/` (left to right)
4. **A**ddition `+` and **S**ubtraction `-` (left to right)
"""

# PEMDAS Example
# 1. Parentheses first: (3 + 1) = 4
# 2. Multiplication next: 4 * 2 = 8
# 3. Subtraction last: 10 - 8 = 2
result = 10 - (3 + 1) * 2
print(result)  # Output: 2

"""## 8. The `round()` Function

The `round()` function is used to round a floating-point number to a specified number of decimals.

**Syntax:** `round(value, number_of_digits)`
"""

# Rounding to 2 decimal places
print(round(8 / 3, 2))  # Output: 2.67

# If you don't specify the digits, it rounds to the nearest whole integer
print(round(2.6))       # Output: 3

"""## 9. Assignment Operators (Shortcuts)

Normally, if you want to update a variable based on its current value, you write it like this:
`count = count + 1`

Think of this like a sentence: *"Take the current value of count, add 1 to it, and save it back into count."*

Because programmers do this all the time, Python created a **shortcut syntax** using `+=`, `-=`, `*=`, and `/=`. Instead of typing the variable name twice, you combine the math sign and the equals sign:
"""

# --- The Long Way ---
count = 0
count = count + 1
print("Long way:", count) # Output: 1

# --- The Shortcut Way (Does the exact same thing!) ---
score = 0
score += 1  # Same as: score = score + 1
print("Shortcut +=", score) # Output: 1

score -= 1  # Same as: score = score - 1
print("Shortcut -=", score) # Output: 0

wallet = 10
wallet *= 2 # Same as: wallet = wallet * 2
print("Shortcut *=", wallet) # Output: 20

wallet /= 4 # Same as: wallet = wallet / 4
print("Shortcut /=", wallet) # Output: 5.0

"""## 10. f-Strings (Formatted Strings)

Before f-strings, if you wanted to print a sentence mixing strings, integers, and floats, you had to manually convert everything to a string using `str()` and paste them together with `+`. It was messy!

An **f-string** allows you to insert any data type directly inside a string by putting an `f` right before the opening quote. You just place your variables inside curly braces `{}`. Python automatically converts everything inside the braces into string format for you.
"""

name = "Aali"
age = 22
CGPA = 9.5

# The old, messy way:
# print("Hi, my name is " + name + ". I am " + str(age) + " years old with a CGPA of " + str(CGPA))

# The clean f-string way:
print(f"Hi, my name is {name}. I am {age} years old with a CGPA of {CGPA}.")
# Output: Hi, my name is Aali. I am 22 years old with a CGPA of 9.5.