# -*- coding: utf-8 -*-
"""Day 1 Learnings and Lessons

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lfwNqNBrVKndIStQB1JvctrNuqAiekyR
"""

#python day 1
print("Hi")
#print() is a fundamental function used by coders to command the computer to perform a certain task, as we write print and then in parenthesis, we mention what is to be printed.
#the input or the feed in the parenthesis could be in text format (need to use "double quotes"), or a digit/value or a variable and even a function.

print(1)
print("Aali")

#Now we know that at times we don't desire to write the print function again and again and wish to simply mention the sentences using single command yet in different lines.
#thus for that we use "\n"
#eg:
print("Hi Aals.\n How are you?")

#You saw that we are just using the text data type, this data type is actually called strings. Just like how the characters are stringed together.
#From here we learn the concept of Concatenation. Meaning joining 2 strings end to end in a way that where string 1 ends the second string begins.
#eg:
print("Hello"+"Aali")
#String 1 is Hello and String 2 is Aali. Also the symbol of concatenation is +.
#Now there is a spacing issue that arises with concatenation. So to give ample space we have to manually give space.
#3 ways we can opt:
print("Hello "+"Aali") #space after Hello
print("Hello"+" Aali")#space before Aali
print ("Hello"+" "+"Aali") #using"" to denote empty blank or space

#Now we are done with outputs, so let's begin with inputs. For getting input from users we use input() function.
#using this input function we prompt the user by asking them and then using the user's input lead ahead.
#all the input so received  by default are of string data type.
#thus there is only one issue with the input function that they don't store the user entered value anywhere thus reusing them can be difficult.
#so to store the user entered values we use variables
#variables are like container that stores value temporarily so that the value can be used later.
#variables can be names as per the requirement and convenience , thus not to be using keywords as the name nor should it start with any digit.

input("Enter your name! ")

#1st way
print("Hi " +  input("Enter your name! "))
#2nd way
name = input("Enter your name : ")
print("Hi"+" "+name+" !")

#One of the ways we can understand more about strings is by string manipulation techniques
# One such way is using len() function to determine the number of characters in a string

name= "Aali Sahay"

print(len(name))

#Exercise 1 Swapping Liquid

Glass1 = "Juice"
Glass2 = "Milk"

Mug = Glass1
Glass1= Glass2
Glass2 = Mug

print(Glass1, Glass2)

#Exercise 2 Band Name Generator
print("Hey there!Let's generate and fun name for your band!")
city = input("Where were you born?")
pet =input("What was your pet's name?")

print("Your Band name is "+ city+pet +" !")