# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RvOhENHbffXSZyDBAbSzy79tDfI6wppo
"""

# Commented out IPython magic to ensure Python compatibility.
# %%html
# <!DOCTYPE html>
# <html lang="en">
# <head>
#     <meta charset="UTF-8">
#     <style>
#         :root {
#             --bg-color: #fdfbf7;
#             --text-color: #4a5568;
#             --glass-border: rgba(143, 168, 155, 0.4);
#             --milk-color: #f4f0ea;
#             --juice-color: #e5a93b;
#         }
# 
#         .lab-wrapper {
#             font-family: 'Segoe UI', system-ui, sans-serif;
#             background-color: var(--bg-color);
#             color: var(--text-color);
#             display: flex;
#             flex-direction: column;
#             align-items: center;
#             justify-content: center;
#             padding: 30px;
#             border-radius: 12px;
#             border: 1px solid rgba(0,0,0,0.05);
#         }
# 
#         .laboratory {
#             display: flex;
#             align-items: flex-end;
#             gap: 40px;
#             margin: 30px 0;
#             height: 160px;
#         }
# 
#         .glass-container {
#             display: flex;
#             flex-direction: column;
#             align-items: center;
#             gap: 12px;
#         }
# 
#         .label {
#             font-size: 0.75rem;
#             text-transform: uppercase;
#             letter-spacing: 1.5px;
#             font-weight: 600;
#             opacity: 0.7;
#         }
# 
#         .glass {
#             width: 75px;
#             height: 120px;
#             border: 3px solid var(--glass-border);
#             border-bottom-left-radius: 18px;
#             border-bottom-right-radius: 18px;
#             border-top-left-radius: 4px;
#             border-top-right-radius: 4px;
#             position: relative;
#             overflow: hidden;
#             background: rgba(255, 255, 255, 0.6);
#         }
# 
#         .mug { width: 85px; height: 100px; border-radius: 6px; }
#         .mug::after {
#             content: '';
#             position: absolute;
#             right: -18px;
#             top: 20px;
#             width: 15px;
#             height: 45px;
#             border: 3px solid var(--glass-border);
#             border-left: none;
#             border-radius: 0 12px 12px 0;
#         }
# 
#         .liquid {
#             position: absolute;
#             bottom: 0;
#             width: 100%;
#             height: 80%;
#             transition: height 0.6s ease-in-out, background-color 0.4s ease;
#         }
# 
#         .milk { background-color: var(--milk-color); box-shadow: inset -5px 0 10px rgba(0,0,0,0.02); }
#         .juice { background-color: var(--juice-color); box-shadow: inset -5px 0 10px rgba(0,0,0,0.04); }
#         .empty { height: 0%; }
# 
#         .btn {
#             background-color: transparent;
#             border: 1px solid var(--text-color);
#             color: var(--text-color);
#             padding: 10px 24px;
#             font-size: 0.8rem;
#             letter-spacing: 1.5px;
#             text-transform: uppercase;
#             cursor: pointer;
#             border-radius: 4px;
#             transition: all 0.3s ease;
#         }
# 
#         .btn:hover:not(:disabled) {
#             background-color: var(--text-color);
#             color: var(--bg-color);
#         }
# 
#         .console {
#             margin-top: 25px;
#             font-family: monospace;
#             font-size: 0.85rem;
#             background: #f4f1eb;
#             padding: 12px 20px;
#             border-radius: 6px;
#             min-width: 260px;
#             text-align: center;
#             border: 1px solid rgba(0,0,0,0.04);
#         }
#     </style>
# </head>
# <body>
# 
# <div class="lab-wrapper">
#     <h2>The Swap Logic</h2>
#     <p style="margin: 0; opacity: 0.7; font-size: 0.9rem;">Visualizing variable assignment step-by-step</p>
# 
#     <div class="laboratory">
#         <div class="glass-container">
#             <div class="glass"><div id="colab_l1" class="liquid milk"></div></div>
#             <div class="label" id="colab_lbl1">Glass 1: Milk</div>
#         </div>
# 
#         <div class="glass-container">
#             <div class="glass mug"><div id="colab_lm" class="liquid empty"></div></div>
#             <div class="label" id="colab_lblm">Mug: Empty</div>
#         </div>
# 
#         <div class="glass-container">
#             <div class="glass"><div id="colab_l2" class="liquid juice"></div></div>
#             <div class="label" id="colab_lbl2">Glass 2: Juice</div>
#         </div>
#     </div>
# 
#     <button class="btn" id="colab_btn" onclick="runColabSwap()">Run Code</button>
#     <div class="console" id="colab_out">// Click "Run Code" to execute</div>
# </div>
# 
# <script>
#     var g1State = "Milk", g2State = "Juice", mState = "Empty";
# 
#     function colabSleep(ms) {
#         return new Promise(function(resolve) { setTimeout(resolve, ms); });
#     }
# 
#     async function runColabSwap() {
#         var btn = document.getElementById('colab_btn');
#         var out = document.getElementById('colab_out');
# 
#         if(btn.innerText === "RESET EXPERIMENT") {
#             resetColab();
#             return;
#         }
# 
#         btn.disabled = true;
# 
#         // Step 1
#         out.innerHTML = "<span style='color: #a67c52; font-weight: bold;'>Mug = Glass1</span>";
#         document.getElementById('colab_l1').className = "liquid empty";
#         document.getElementById('colab_lm').className = "liquid milk";
#         document.getElementById('colab_lbl1').innerText = "Glass 1: Empty";
#         document.getElementById('colab_lblm').innerText = "Mug: Milk";
#         await colabSleep(1200);
# 
#         // Step 2
#         out.innerHTML = "<span style='color: #a67c52; font-weight: bold;'>Glass1 = Glass2</span>";
#         document.getElementById('colab_l2').className = "liquid empty";
#         document.getElementById('colab_l1').className = "liquid juice";
#         document.getElementById('colab_lbl2').innerText = "Glass 2: Empty";
#         document.getElementById('colab_lbl1').innerText = "Glass 1: Juice";
#         await colabSleep(1200);
# 
#         // Step 3
#         out.innerHTML = "<span style='color: #a67c52; font-weight: bold;'>Glass2 = Mug</span>";
#         document.getElementById('colab_lm').className = "liquid empty";
#         document.getElementById('colab_l2').className = "liquid milk";
#         document.getElementById('colab_lblm').innerText = "Mug: Empty";
#         document.getElementById('colab_lbl2').innerText = "Glass 2: Milk";
#         await colabSleep(1200);
# 
#         // Step 4
#         out.innerHTML = "<strong>print(Glass1, Glass2)</strong><br><br>👉 Output: 'Juice', 'Milk'";
#         btn.innerText = "RESET EXPERIMENT";
#         btn.disabled = false;
#     }
# 
#     function resetColab() {
#         document.getElementById('colab_l1').className = "liquid milk";
#         document.getElementById('colab_l2').className = "liquid juice";
#         document.getElementById('colab_lm').className = "liquid empty";
#         document.getElementById('colab_lbl1').innerText = "Glass 1: Milk";
#         document.getElementById('colab_lbl2').innerText = "Glass 2: Juice";
#         document.getElementById('colab_lblm').innerText = "Mug: Empty";
#         document.getElementById('colab_out').innerHTML = "// Click 'Run Code' to execute";
#         document.getElementById('colab_btn').innerText = "Run Code";
#     }
# </script>
# 
# </body>
# </html>